### ISSUE TITLE
Playstore alternative

### ISSUE THREAD

**Issue by IzzySoft** [thuetz/Energize#40]
Would you mind attaching a "prebuilt version" to your `releases/` at Github – especially for folks without Playstore? I'd then offer you to ship it via [my F-Droid compatible repo](https://android.izzysoft.de/repo) for easier updates.

**Comment by thuetz** [comment]
Thank you for your message. I thought about it and came to the conclusion that it is a good idea to provide the app as a pre-build APK. Users can download the app now from the corresponding release on the github.com page (e.g. https://github.com/thuetz/Energize/releases/tag/v2.0). However, I am not so convinced with bundling the app with your repo. Who would ensure that always the latest app is available there?

**Comment by IzzySoft** [comment]
Good point. I forgot to mention my auto-updater: within 24h of your attaching the `.apk` to a new tag/release, it's automatically grabbed and my repo updated. In rare cases (e.g. if you or some other "participant" forgot to increase the `versionCode`/`versionName` in the new APK, which would lead to a "duplicate", have the repo update fail, and sending me a warning) I need to manually intervent and fix things; but unless I'm on vacation that happens the same day as well (and has no impact on the availability of the previous version, as in such cases the index is not updated before the error is fixed).

Some other projects here at Github even pointed out that "updates are available faster than on the official repo" :smile_cat:

**Comment by thuetz** [comment]
Thank you for your reply and also the notice about my missing license file. I have added the missing license file (GPLv3). I am now also convinced that your idea of publishing this app in your repository is also a good idea. Thanks for providing such a service to the community.

**Comment by IzzySoft** [comment]
You're welcome anytime! I'm not an Android dev, so I just chose a different form to contribute to the FOSS community. As it should be, it lives from giving and taking, which both must be somehow in balance 😸 

Thanks for adding the license. I will update the record in my repo this evening to reflect that. Be welcome to add above link (as with Playstore & Co, it will stay the same as long as the package name does not change) to the "Download a pre-build version" section of the `README.md` :wink:

**Comment by IzzySoft** [comment]
@Perflyst The app uses GMS, which is a show-stopper for the main repo. If that dependency can be removed (e.g. using a separate flavor), that would of course be a great way to go.
