### ISSUE TITLE
Get bug || Energize Battery Monitor Estimation Currently Not Available 

### ISSUE THREAD

**Issue by Gentasteem** [thuetz/Energize#43]
#### Expected behavior<br>
The estimated battery power is visible in the bar section.<br>
<br>
#### Actual behavior<br>
<br>
The reality is that &quot;Estimation currently not available&quot;<br>
<br>
#### How to reproduce<br>
<br>
* Download the Energize - Battery monitor app on playstore Or [Here](https://play.google.com/store/apps/details?id=com.halcyonwaves.apps.energize)
* Launch application<br>
* Click Ok button<br>
* Drag the screen down to see the app work in progress.<br>
<br>
- Device used: Samsung Grand prime SM-G530<br>
<br>
* Operating System: Android version 4.4.4<br>
<br>
* Application version: 2.2 (220)<br>
<br>
#### Recording Of The Bug<br>
<br>
https://youtu.be/0hUu4POQopQ<br>

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@gentasteem/get-bug-or-or-energize-battery-monitor-estimation-currently-not-available">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by thuetz** [comment]
Thank you for your bug report. It takes some time the app has to run in the background to collect information for predicting the remaining time. Might it be that you just installed the app and this was the first start?

**Comment by thuetz** [comment]
Since there are no more responses I'll close this issue until we have more information.
