### ISSUE TITLE
Battery Information not viewable in Landscape Mode

### ISSUE THREAD

**Issue by tobias-g1** [thuetz/Energize#45]
#### Expected behaviour
I should be able to view all of the battery information regardless of my screen orientation, the battery information should be scrollable allowing me to see my battery information in landscape mode. 

#### Actual behavior
The battery information is not viewable in landscape mode and you cannot scroll to view the battery information. The information which cannot be viewed includes the following: Changing State, Battery Temperature, Time on Battery, Remaining Time

#### How to reproduce
1.  Download the application here:https://play.google.com/store/apps/details?id=com.halcyonwaves.apps.energize
2. Install & Start Application, launch the application with your device display in portrait.
3. Note the information shown on screen.
4. With the ability to rotate your screen enabled,  rotate your device. 
5. When in landscape mode, try and scroll down to view the battery information. 

#### Environment Details

 - Application Version: 2.2
- Operating system: Android 5.0.2
- Device: Samsung Galaxy Alpha
- Model Number: SM-G850F

#### Recording Of The Bug
An image which shows the bug can be seen here (Apologies, that my clicks are not captured. When in landscape mode I am attempting to scroll) : 

![ezgif-2-e56b32da47.gif](https://gateway.ipfs.io/ipfs/QmSnANDeLfjnDmgXKJdf2U5sGtsL1FVjyvkKTcXw1ii6o8)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tobias-g/battery-information-not-viewable-in-landscape-mode">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by thuetz** [comment]
Fix by hiding the animation in landscape mode. The bug is already fixed in the master and will be released with the next app update.
