### ISSUE TITLE
Returns to application overview page on screen rotation

### ISSUE THREAD

**Issue by tobias-g1** [thuetz/Energize#46]
#### Expected behaviour
I should be able to switch between screen orientations and remain on the same page of the application. 

#### Actual behavior
When you go into either battery graph or temperature graph and then switch the orientation of my device it will take you back to overview page. 

#### How to reproduce
1.  Download the application here:https://play.google.com/store/apps/details?id=com.halcyonwaves.apps.energize
2. Install & Start Application, launch the application with your device display in portrait.
3. Click on battery graph.
4. Switch the orientation of your screen to landscape.
5. You will be returned to the overview page.
6. Repeat steps 3 to 5 for temperature graph for the same results.

#### Environment Details

 - Application Version: 2.2
- Operating system: Android 5.0.2
- Device: Samsung Galaxy Alpha
- Model Number: SM-G850F

#### Recording Of The Bug
The following image shows this in more detail, this can be viewed below (Note: The video also shows that the application supports these pages in landscape view)

![ezgif-2-eb90b39f31.gif](https://gateway.ipfs.io/ipfs/Qme5wp9gZnZFB54R3rgjXnuhEZHNgqVtSLCyeom9nw9VUn)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tobias-g/returns-to-application-overview-page-on-screen-rotation">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by thuetz** [comment]
The bug is fixed in the master and will be released with the next app update.
